### ISSUE TITLE
After installing the tool doesn't work

### ISSUE THREAD

**Issue by ivanbuzyka** [Sitecore/experience-extractor#1] opened 2015-05-28 12:27 UTC
At least by me and by colleague of mine, we could get the tool working only after cleaning up following folder: "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files". Right after installing it doesn't work (clicking "Submit" button in SPEAK application does nothing).

**Comment by NielsKuhnel** [comment] 2015-10-28 20:35
Sorry for not commenting on this before. Yes, occasionally you had to delete your temp ASP.NET files. I think this was due to the inner workings of the the initial release of 8.0, but I am not sure. I have not been able to reproduce with later updates. Closing.

**Closed by NielsKuhnel** 2015-10-28 20:35 UTC
